In [2]:
import pandas as pd
df1 = pd.read_csv('combined_fight_odds_916.csv')
df2 = pd.read_csv('fights_odds_paris_fighters.csv')
# missing_fights_916
# Concatenate the DataFrames
# combined_df = pd.concat([df1, df2, df3, df4, df5, df6])
combined_df = pd.concat([df1, df2])

# Drop duplicate rows
combined_df = combined_df.drop_duplicates()

# Reset the index
combined_df = combined_df.reset_index(drop=True)

# Display the final DataFrame
print(len(combined_df))
# df.head()

12007

In [3]:
combined_df.head()

,Unnamed: 0,Fighter,Fighter Odds,Opponent,Opponent Odds,Event,Date
0,0.0,Alexander Gustafsson,340.0,Phil Davis,-465.0,UFC 112: Invincible,Apr 10th 2010
1,1.0,Anderson Silva,-560.0,Demian Maia,405.0,UFC 112: Invincible,Apr 10th 2010
2,2.0,Brad Blackburn,-170.0,Damarques Johnson,140.0,UFC 112: Invincible,Apr 10th 2010
3,3.0,Demian Maia,405.0,Anderson Silva,-560.0,UFC 112: Invincible,Apr 10th 2010
4,4.0,Frankie Edgar,525.0,B.J. Penn,-750.0,UFC 112: Invincible,Apr 10th 2010

In [4]:
# Sort rows to ensure consistent ordering
df_sorted = combined_df.sort_values(by=['Date', 'Fighter', 'Opponent']).reset_index(drop=True)

# Create a boolean mask to identify duplicates based on the condition
duplicates_mask = (
    (df_sorted['Fighter'] == df_sorted['Opponent'].shift()) &
    (df_sorted['Opponent'] == df_sorted['Fighter'].shift()) &
    (df_sorted['Date'] == df_sorted['Date'].shift())
)

# Filter the DataFrame to remove duplicates
df_no_duplicates = df_sorted[~duplicates_mask].reset_index(drop=True)

# Display the DataFrame without duplicates
print(df_no_duplicates)
print(len(df_no_duplicates))

       Unnamed: 0               Fighter  Fighter Odds           Opponent  \
0             0.0  Alexander Gustafsson         340.0         Phil Davis
1             1.0        Anderson Silva        -560.0        Demian Maia
2             2.0        Brad Blackburn        -170.0  Damarques Johnson
3             3.0           Demian Maia         405.0     Anderson Silva
4             4.0         Frankie Edgar         525.0          B.J. Penn
...           ...                   ...           ...                ...
11993     11826.0           Wilson Reis         300.0       Henry Cejudo
11994     11827.0       Gabriel Miranda         128.0        Shane Young
11995         NaN       Gabriel Miranda         128.0        Shane Young
11996     11828.0        Kiefer Crosbie         110.0      Kevin Jousset
11997     11829.0           Shane Young        -155.0    Gabriel Miranda

       Opponent Odds                            Event           Date
0             -465.0              UFC 112: Invincible  Apr 10th 2010
1              405.0              UFC 112: Invincible  Apr 10th 2010
2              140.0              UFC 112: Invincible  Apr 10th 2010
3             -560.0              UFC 112: Invincible  Apr 10th 2010
4             -750.0              UFC 112: Invincible  Apr 10th 2010
...              ...                              ...            ...
11993         -420.0  UFC 215: Nunes vs. Shevchenko 2   Sep 9th 2017
11994         -155.0                          UFC 293   Sep 9th 2023
11995         -155.0                          UFC 293   Sep 9th 2023
11996         -135.0                          UFC 293   Sep 9th 2023
11997          128.0                          UFC 293   Sep 9th 2023

[11998 rows x 7 columns]
11998

In [6]:
df = df_no_duplicates

In [7]:
# df = df_no_duplicates
# Combine the 'Fighter' and 'Opponent' columns
combined_names = pd.concat([df['Fighter'], df['Opponent']])

# Get unique names
unique_names = combined_names.unique()

# Convert to a list (optional)
unique_names_list = list(unique_names)

In [8]:
df.head()

,Unnamed: 0,Fighter,Fighter Odds,Opponent,Opponent Odds,Event,Date
0,0.0,Alexander Gustafsson,340.0,Phil Davis,-465.0,UFC 112: Invincible,Apr 10th 2010
1,1.0,Anderson Silva,-560.0,Demian Maia,405.0,UFC 112: Invincible,Apr 10th 2010
2,2.0,Brad Blackburn,-170.0,Damarques Johnson,140.0,UFC 112: Invincible,Apr 10th 2010
3,3.0,Demian Maia,405.0,Anderson Silva,-560.0,UFC 112: Invincible,Apr 10th 2010
4,4.0,Frankie Edgar,525.0,B.J. Penn,-750.0,UFC 112: Invincible,Apr 10th 2010

In [9]:
df = df.drop('Unnamed: 0', axis=1)

In [10]:
df.head()

,Fighter,Fighter Odds,Opponent,Opponent Odds,Event,Date
0,Alexander Gustafsson,340.0,Phil Davis,-465.0,UFC 112: Invincible,Apr 10th 2010
1,Anderson Silva,-560.0,Demian Maia,405.0,UFC 112: Invincible,Apr 10th 2010
2,Brad Blackburn,-170.0,Damarques Johnson,140.0,UFC 112: Invincible,Apr 10th 2010
3,Demian Maia,405.0,Anderson Silva,-560.0,UFC 112: Invincible,Apr 10th 2010
4,Frankie Edgar,525.0,B.J. Penn,-750.0,UFC 112: Invincible,Apr 10th 2010

In [7]:
# df = df[df['Event'].str.contains('UFC', na=False)]

In [8]:
print(len(unique_names_list))

2357

In [9]:
import pandas as pd
dff = pd.read_csv('all_fighters.csv')
print(len(dff))
dff.head()

4222

,First,Last,Nickname,Ht,Wt,Reach,Stance,W,L,D,...,SLpM,Str. Acc.,SApM,Str. Def,Unnamed: 15,TD Avg.,TD Acc.,TD Def.,Sub. Avg.,DOB
0,Hunter,Azure,NaN,"5' 8""",145 lbs.,"69.0""",Orthodox,9,2,0,...,3.92,53%,2.08,58%,NaN,1.97,34%,67%,1.3,"Mar 02, 1992"
1,Bartosz,Fabinski,The Butcher,"6' 0""",170 lbs.,"75.0""",Orthodox,15,5,0,...,2.23,68%,1.46,51%,NaN,7.10,70%,80%,0.0,"Apr 26, 1986"
2,Wagnney,Fabiano,The Silencer,"5' 6""",145 lbs.,"69.0""",Southpaw,16,4,0,...,1.19,38%,0.66,70%,NaN,3.44,64%,100%,0.4,"Jul 14, 1975"
3,Marcos,da Matta,Parrumpinha,"5' 4""",145 lbs.,--,NaN,11,3,0,...,0.00,0%,0.00,0%,NaN,0.00,0%,0%,0.0,"Mar 18, 1973"
4,Brandon,Davis,Killer B,"5' 10""",135 lbs.,"72.0""",Orthodox,14,10,0,...,4.68,35%,4.62,58%,NaN,0.74,42%,57%,0.1,"May 08, 1990"

In [11]:
df.to_csv("combined_fight_odds_928.csv")

In [19]:
names = pd.read_csv('fighter_names.csv')

In [20]:
print(len(names))

4222

In [21]:
# Combine Fighter and Opponent into one set of unique fighters
existing_fighters = set(df['Fighter']).union(set(df['Opponent']))

names['Name'] = names['Name'].str.replace('-', ' ')

# Find fighters in names that are not in the first dataframe
missing_fighters = names[~names['Name'].isin(existing_fighters)]

# Replace hyphens with spaces in the 'Name' column
# missing_fighters['Name'] = missing_fighters['Name'].str.replace('-', ' ')

# Create new dataframe with missing fighters
missing_fighters_df = pd.DataFrame(missing_fighters)

missing_fighters_df['Name'] = missing_fighters_df['Name'].str.replace(' ', '-')

print(missing_fighters_df)

      Unnamed: 0               Name
2              2    Wagnney-Fabiano
3              3    Marcos-da-Matta
5              5        Dave-Galera
7              7      Devin-Johnson
8              8         Nate-James
...          ...                ...
4215        4215      Oleg-Taktarov
4216        4216      Murtaza-Talha
4217        4217    Makoto-Takimoto
4218        4218  Yoshiki-Takahashi
4219        4219    Nobuhiko-Takada

[2175 rows x 2 columns]

In [22]:
# Drop 'Unnamed: 0' column
missing_fighters_df = missing_fighters_df.drop('Unnamed: 0', axis=1)

print(missing_fighters_df)

                   Name
2       Wagnney-Fabiano
3       Marcos-da-Matta
5           Dave-Galera
7         Devin-Johnson
8            Nate-James
...                 ...
4215      Oleg-Taktarov
4216      Murtaza-Talha
4217    Makoto-Takimoto
4218  Yoshiki-Takahashi
4219    Nobuhiko-Takada

[2175 rows x 1 columns]

In [23]:
missing_fighters_df.to_csv("missing_fighters_916.csv")

In [28]:
df2 = pd.read_csv('fights_odds_307_fighters.csv')

In [29]:
len(df2)

280

In [30]:
import pandas as pd

# Iterate through each row with index
rows_to_drop = set()
for idx1, row1 in df2.iterrows():
    # Check all subsequent rows
    for idx2, row2 in df2.iterrows():
        if idx1 != idx2 and idx2 not in rows_to_drop and idx1 not in rows_to_drop:
            # Check if "Fighter 1", "Fighter 2", and "Date" are the same
            if (
                (row1['Fighter'] == row2['Fighter'] and
                row1['Opponent'] == row2['Opponent'] and
                row1['Date'] == row2['Date']) | 
                (row1['Opponent'] == row2['Fighter'] and
                row1['Fighter'] == row2['Opponent'] and
                row1['Date'] == row2['Date'])
            ):
                # Mark the second row for dropping
                print(idx2)
                rows_to_drop.add(idx2)

# Drop the matching rows
odds_cleaned = df2.drop(index=list(rows_to_drop))

# Inspect cleaned dataframe
print(odds_cleaned)

148
249
160
55
250
152
227
139
166
178
110
180
199
231
255
          Fighter  Fighter Odds             Opponent  Opponent Odds  \
0    Alex Pereira        -535.0  Khalil Rountree Jr.          400.0
1    Alex Pereira        -135.0       Jiri Prochazka          114.0
2    Alex Pereira        -163.0         Jamahal Hill          130.0
3    Alex Pereira         105.0       Jiri Prochazka         -138.0
4    Alex Pereira         128.0       Jan Brachowicz         -164.0
..            ...           ...                  ...            ...
275     Tim Means        -190.0     Daniel Rodriguez          150.0
276     Tim Means        -160.0         Thiago Alves          130.0
277     Tim Means         125.0       Danny Castillo         -165.0
278     Tim Means         125.0       Jorge Masvidal         -165.0
279     Tim Means        -150.0         Justin Salas          120.0

                                          Event           Date
0                                           UFC   Oct 6th 2024
1                                       UFC 303  Jun 30th 2024
2                                       UFC 300  Apr 14th 2024
3                                           UFC  Nov 12th 2023
4                                           UFC  Jul 30th 2023
..                                          ...            ...
275  UFC on ESPN+ 25: Anderson vs. Blachowicz 2  Feb 15th 2020
276      UFC on ESPN 7: Overeem vs. Rozenstruik   Dec 7th 2019
277            UFC on FOX 8: Johnson vs. Moraga  Jul 27th 2013
278        UFC on FOX 7: Henderson vs. Melendez  Apr 20th 2013
279             UFC on FX 3: Johnson vs. McCall   Jun 8th 2012

[265 rows x 6 columns]

In [31]:
odds_cleaned.head()

,Fighter,Fighter Odds,Opponent,Opponent Odds,Event,Date
0,Alex Pereira,-535.0,Khalil Rountree Jr.,400.0,UFC,Oct 6th 2024
1,Alex Pereira,-135.0,Jiri Prochazka,114.0,UFC 303,Jun 30th 2024
2,Alex Pereira,-163.0,Jamahal Hill,130.0,UFC 300,Apr 14th 2024
3,Alex Pereira,105.0,Jiri Prochazka,-138.0,UFC,Nov 12th 2023
4,Alex Pereira,128.0,Jan Brachowicz,-164.0,UFC,Jul 30th 2023

In [32]:
odds_cleaned.to_csv("307_odds_clean.csv")

In [39]:
combo = pd.read_csv('combined_fight_odds_916.csv', index_col=0)

In [40]:
# Definition

# Create a helper column to normalize Fighter 1 and Fighter 2 pairs
combo['fighter_pair'] = combo.apply(lambda row: tuple(sorted([row['Fighter'], row['Opponent']])), axis=1)

# Drop duplicate rows based on 'fighter_pair' and 'Date'
combo_cleaned = combo.drop_duplicates(subset=['fighter_pair', 'Date'])

# Drop the helper column
combo_cleaned = combo_cleaned.drop(columns=['fighter_pair'])

# Inspect cleaned dataframe
print(combo_cleaned)

                    Fighter  Fighter Odds            Opponent  Opponent Odds  \
0      Alexander Gustafsson         340.0          Phil Davis         -465.0
1            Anderson Silva        -560.0         Demian Maia          405.0
2            Brad Blackburn        -170.0   Damarques Johnson          140.0
4             Frankie Edgar         525.0           B.J. Penn         -750.0
5                Jon Madsen        -300.0    Mostapha Al-Turk          240.0
...                     ...           ...                 ...            ...
11818         Ketlen Vieira         185.0         Sara McMann         -265.0
11821            Neil Magny         140.0    Rafael Dos Anjos         -180.0
11823           Sarah Moras         175.0  Ashlee Evans-Smith         -245.0
11827       Gabriel Miranda         128.0         Shane Young         -155.0
11828        Kiefer Crosbie         110.0       Kevin Jousset         -135.0

                                 Event           Date
0                  UFC 112: Invincible  Apr 10th 2010
1                  UFC 112: Invincible  Apr 10th 2010
2                  UFC 112: Invincible  Apr 10th 2010
4                  UFC 112: Invincible  Apr 10th 2010
5                  UFC 112: Invincible  Apr 10th 2010
...                                ...            ...
11818  UFC 215: Nunes vs. Shevchenko 2   Sep 9th 2017
11821  UFC 215: Nunes vs. Shevchenko 2   Sep 9th 2017
11823  UFC 215: Nunes vs. Shevchenko 2   Sep 9th 2017
11827                          UFC 293   Sep 9th 2023
11828                          UFC 293   Sep 9th 2023

[7175 rows x 6 columns]

In [41]:
combo_cleaned.to_csv('combined_fight_odds_928_2.csv')

In [42]:
combo_cleaned

,Fighter,Fighter Odds,Opponent,Opponent Odds,Event,Date
0,Alexander Gustafsson,340.0,Phil Davis,-465.0,UFC 112: Invincible,Apr 10th 2010
1,Anderson Silva,-560.0,Demian Maia,405.0,UFC 112: Invincible,Apr 10th 2010
2,Brad Blackburn,-170.0,Damarques Johnson,140.0,UFC 112: Invincible,Apr 10th 2010
4,Frankie Edgar,525.0,B.J. Penn,-750.0,UFC 112: Invincible,Apr 10th 2010
5,Jon Madsen,-300.0,Mostapha Al-Turk,240.0,UFC 112: Invincible,Apr 10th 2010
...,...,...,...,...,...,...
11818,Ketlen Vieira,185.0,Sara McMann,-265.0,UFC 215: Nunes vs. Shevchenko 2,Sep 9th 2017
11821,Neil Magny,140.0,Rafael Dos Anjos,-180.0,UFC 215: Nunes vs. Shevchenko 2,Sep 9th 2017
11823,Sarah Moras,175.0,Ashlee Evans-Smith,-245.0,UFC 215: Nunes vs. Shevchenko 2,Sep 9th 2017
11827,Gabriel Miranda,128.0,Shane Young,-155.0,UFC 293,Sep 9th 2023
11828,Kiefer Crosbie,110.0,Kevin Jousset,-135.0,UFC 293,Sep 9th 2023

In [43]:
new = pd.concat([combo_cleaned, odds_cleaned], axis=0, ignore_index=True)

In [44]:
new.to_csv('all_fight_odds_w307_929.csv')

In [45]:
combo = new

In [46]:
# Create a helper column to normalize Fighter 1 and Fighter 2 pairs
combo['fighter_pair'] = combo.apply(lambda row: tuple(sorted([row['Fighter'], row['Opponent']])), axis=1)

# Drop duplicate rows based on 'fighter_pair' and 'Date'
combo_cleaned = combo.drop_duplicates(subset=['fighter_pair', 'Date'])

# Drop the helper column
combo_cleaned = combo_cleaned.drop(columns=['fighter_pair'])

# Inspect cleaned dataframe
print(combo_cleaned)

                   Fighter  Fighter Odds           Opponent  Opponent Odds  \
0     Alexander Gustafsson         340.0         Phil Davis         -465.0
1           Anderson Silva        -560.0        Demian Maia          405.0
2           Brad Blackburn        -170.0  Damarques Johnson          140.0
3            Frankie Edgar         525.0          B.J. Penn         -750.0
4               Jon Madsen        -300.0   Mostapha Al-Turk          240.0
...                    ...           ...                ...            ...
7199         Cesar Almeida        -333.0      Ihor Potieria          250.0
7202           Court McGee         190.0          Tim Means         -230.0
7224        Iasmin Lucindo        -120.0   Marina Rodriguez         -110.0
7282        Kayla Harrison        -649.0      Ketlen Vieira          400.0
7376            Ryan Spann        -330.0   Ovince St. Preux          260.0

                    Event           Date
0     UFC 112: Invincible  Apr 10th 2010
1     UFC 112: Invincible  Apr 10th 2010
2     UFC 112: Invincible  Apr 10th 2010
3     UFC 112: Invincible  Apr 10th 2010
4     UFC 112: Invincible  Apr 10th 2010
...                   ...            ...
7199              UFC 307   Oct 5th 2024
7202              UFC 307   Oct 5th 2024
7224              UFC 307   Oct 5th 2024
7282              UFC 307   Oct 5th 2024
7376              UFC 307   Oct 5th 2024

[7181 rows x 6 columns]

In [47]:
combo_cleaned.to_csv('all_fight_odds_w307_929_2.csv')