In [2]:
import pandas as pd
import numpy as np

In [3]:
# read data for fights and fighters
fighters = pd.read_csv("all_fighters.csv")

Next, We will perform a series of steps to clean up the datasets.

In [4]:
fighters.head()

,First,Last,Nickname,Ht,Wt,Reach,Stance,W,L,D,...,SLpM,Str. Acc.,SApM,Str. Def,Unnamed: 15,TD Avg.,TD Acc.,TD Def.,Sub. Avg.,DOB
0,Hunter,Azure,NaN,"5' 8""",145 lbs.,"69.0""",Orthodox,9,2,0,...,3.92,53%,2.08,58%,NaN,1.97,34%,67%,1.3,"Mar 02, 1992"
1,Bartosz,Fabinski,The Butcher,"6' 0""",170 lbs.,"75.0""",Orthodox,15,5,0,...,2.23,68%,1.46,51%,NaN,7.10,70%,80%,0.0,"Apr 26, 1986"
2,Wagnney,Fabiano,The Silencer,"5' 6""",145 lbs.,"69.0""",Southpaw,16,4,0,...,1.19,38%,0.66,70%,NaN,3.44,64%,100%,0.4,"Jul 14, 1975"
3,Marcos,da Matta,Parrumpinha,"5' 4""",145 lbs.,--,NaN,11,3,0,...,0.00,0%,0.00,0%,NaN,0.00,0%,0%,0.0,"Mar 18, 1973"
4,Brandon,Davis,Killer B,"5' 10""",135 lbs.,"72.0""",Orthodox,14,10,0,...,4.68,35%,4.62,58%,NaN,0.74,42%,57%,0.1,"May 08, 1990"

In [5]:
fighters['Name'] = fighters['First'].fillna('') + ' ' + fighters['Last'].fillna('')

# Strip any leading or trailing whitespace (in case both First and Last are NaN)
fighters['Name'] = fighters['Name'].str.strip()

# # check if there are fighters with the same name
# fighters[fighters.duplicated(subset="Name", keep=False)]

In [11]:
fighters[fighters.duplicated(subset="Name", keep=False)]

KeyError: Index(['Name'], dtype='object')

In [7]:
columns = ['Name'] + [col for col in fighters.columns if col != 'Name']
fighters = fighters[columns]
fighters.head()

,Name,First,Last,Nickname,Ht,Wt,Reach,Stance,W,L,...,SLpM,Str. Acc.,SApM,Str. Def,Unnamed: 15,TD Avg.,TD Acc.,TD Def.,Sub. Avg.,DOB
0,Hunter Azure,Hunter,Azure,NaN,"5' 8""",145 lbs.,"69.0""",Orthodox,9,2,...,3.92,53%,2.08,58%,NaN,1.97,34%,67%,1.3,"Mar 02, 1992"
1,Bartosz Fabinski,Bartosz,Fabinski,The Butcher,"6' 0""",170 lbs.,"75.0""",Orthodox,15,5,...,2.23,68%,1.46,51%,NaN,7.10,70%,80%,0.0,"Apr 26, 1986"
2,Wagnney Fabiano,Wagnney,Fabiano,The Silencer,"5' 6""",145 lbs.,"69.0""",Southpaw,16,4,...,1.19,38%,0.66,70%,NaN,3.44,64%,100%,0.4,"Jul 14, 1975"
3,Marcos da Matta,Marcos,da Matta,Parrumpinha,"5' 4""",145 lbs.,--,NaN,11,3,...,0.00,0%,0.00,0%,NaN,0.00,0%,0%,0.0,"Mar 18, 1973"
4,Brandon Davis,Brandon,Davis,Killer B,"5' 10""",135 lbs.,"72.0""",Orthodox,14,10,...,4.68,35%,4.62,58%,NaN,0.74,42%,57%,0.1,"May 08, 1990"

In [8]:
fighters.drop(3325, inplace=True)
fighters.iloc[3311, 0] = "Bruno Silva 185"
fighters.drop(2627, inplace=True)
fighters.drop(2103, inplace=True)
fighters.iloc[1988, 0] = "Tony Johnson 265"
fighters.iloc[480, 0] = "Michael McDonald 205"

In [9]:
columns = ['Name'] + [col for col in fighters.columns if col != 'Name']
fighters = fighters[columns]
fighters.head()

,Name,First,Last,Nickname,Ht,Wt,Reach,Stance,W,L,...,SLpM,Str. Acc.,SApM,Str. Def,Unnamed: 15,TD Avg.,TD Acc.,TD Def.,Sub. Avg.,DOB
0,Hunter Azure,Hunter,Azure,NaN,"5' 8""",145 lbs.,"69.0""",Orthodox,9,2,...,3.92,53%,2.08,58%,NaN,1.97,34%,67%,1.3,"Mar 02, 1992"
1,Bartosz Fabinski,Bartosz,Fabinski,The Butcher,"6' 0""",170 lbs.,"75.0""",Orthodox,15,5,...,2.23,68%,1.46,51%,NaN,7.10,70%,80%,0.0,"Apr 26, 1986"
2,Wagnney Fabiano,Wagnney,Fabiano,The Silencer,"5' 6""",145 lbs.,"69.0""",Southpaw,16,4,...,1.19,38%,0.66,70%,NaN,3.44,64%,100%,0.4,"Jul 14, 1975"
3,Marcos da Matta,Marcos,da Matta,Parrumpinha,"5' 4""",145 lbs.,--,NaN,11,3,...,0.00,0%,0.00,0%,NaN,0.00,0%,0%,0.0,"Mar 18, 1973"
4,Brandon Davis,Brandon,Davis,Killer B,"5' 10""",135 lbs.,"72.0""",Orthodox,14,10,...,4.68,35%,4.62,58%,NaN,0.74,42%,57%,0.1,"May 08, 1990"

In [10]:
# use fighter names as index
# fighters.drop("fighter_id", axis=1, inplace=True)
fighters.set_index("Name", inplace=True)

In [12]:
# Some fighters do not have statistics available, and we will remove those fighters.
fighters_clean = fighters.loc[~((fighters["SLpM"] == 0) &
                               (fighters["Str. Acc."] == "0%") &
                               (fighters["SApM"] == 0) &
                               (fighters["Str. Def"] == "0%") &
                               (fighters["TD Avg."] == 0) &
                               (fighters["TD Acc."] == "0%") &
                               (fighters["TD Def."] == "0%") &
                               (fighters["Sub. Avg."] == 0))].copy()

In [13]:
print("{0} fighters in total, after clean up: {1} fighters".format(len(fighters), len(fighters_clean)))

4219 fighters in total, after clean up: 3473 fighters

Note:
* SLpM - Significant Strikes Landed per Minute
* Str_Acc - Significant Striking Accuracy
* SApM - Significant Strikes Absorbed per Minute
* Str_Def - Significant Strike Defence (the % of opponents strikes that did not land)
* TD_Avg - Average Takedowns Landed per 15 minutes
* TD_Acc - Takedown Accuracy
* TD_Def - Takedown Defense (the % of opponents TD attempts that did not land)
* Sub_Avg - Average Submissions Attempted per 15 minutes

In [14]:
fighters_clean["win%"] = 100 * (fighters_clean["W"] / (fighters_clean["W"] +
                                                       fighters_clean["L"] +
                                                       fighters_clean["D"]))
                                                      #  fighters_clean["nc"]))  # Assuming nc is not in use

# Columns that have percentages as strings
percentages = ["Str. Acc.", "Str. Def", "TD Acc.", "TD Def."]
# Columns to convert to float32
statistics = ["SLpM", "Str. Acc.", "SApM", "Str. Def", "TD Avg.", "TD Acc.", "TD Def.", "Sub. Avg.", "win%"]

# Remove the '%' sign and convert to float
for col in percentages:
    fighters_clean[col] = fighters_clean[col].map(lambda x: float(x.replace("%", "")) if pd.notna(x) else x)

# Convert statistics columns to float32
fighters_clean[statistics] = fighters_clean[statistics].astype(np.float32, errors='ignore')

print(fighters_clean)

                      First       Last      Nickname      Ht        Wt  Reach  \
Name
Hunter Azure         Hunter      Azure           NaN   5' 8"  145 lbs.  69.0"
Bartosz Fabinski    Bartosz   Fabinski   The Butcher   6' 0"  170 lbs.  75.0"
Wagnney Fabiano     Wagnney    Fabiano  The Silencer   5' 6"  145 lbs.  69.0"
Brandon Davis       Brandon      Davis      Killer B  5' 10"  135 lbs.  72.0"
Dave Galera            Dave     Galera     Scarecrow  5' 11"  135 lbs.     --
...                     ...        ...           ...     ...       ...    ...
Makoto Takimoto      Makoto   Takimoto           NaN   5' 7"  205 lbs.     --
Yoshiki Takahashi   Yoshiki  Takahashi         Kazuo  5' 11"  199 lbs.     --
Nobuhiko Takada    Nobuhiko     Takada           NaN   6' 0"  220 lbs.     --
Mairbek Taisumov    Mairbek   Taisumov        Beckan   5' 9"  155 lbs.  73.0"
Tatsuro Taira       Tatsuro      Taira           NaN   5' 7"  125 lbs.  70.0"

                     Stance   W   L  D  ...  Str. Acc.  SApM  Str. Def  \
Name                                    ...
Hunter Azure       Orthodox   9   2  0  ...       53.0  2.08      58.0
Bartosz Fabinski   Orthodox  15   5  0  ...       68.0  1.46      51.0
Wagnney Fabiano    Southpaw  16   4  0  ...       38.0  0.66      70.0
Brandon Davis      Orthodox  14  10  0  ...       35.0  4.62      58.0
Dave Galera        Orthodox   5   1  0  ...       69.0  0.53      33.0
...                     ...  ..  .. ..  ...        ...   ...       ...
Makoto Takimoto    Southpaw   6   5  0  ...       39.0  1.71      55.0
Yoshiki Takahashi  Southpaw  30  27  3  ...       51.0  6.47      44.0
Nobuhiko Takada    Southpaw   2   6  2  ...       24.0  1.92      39.0
Mairbek Taisumov   Orthodox  27   6  0  ...       39.0  3.03      64.0
Tatsuro Taira      Orthodox  16   0  0  ...       65.0  1.70      47.0

                   Unnamed: 15  TD Avg.  TD Acc.  TD Def.  Sub. Avg.  \
Name
Hunter Azure               NaN     1.97     34.0     67.0        1.3
Bartosz Fabinski           NaN     7.10     70.0     80.0        0.0
Wagnney Fabiano            NaN     3.44     64.0    100.0        0.4
Brandon Davis              NaN     0.74     42.0     57.0        0.1
Dave Galera                NaN     0.00      0.0     14.0        2.0
...                        ...      ...      ...      ...        ...
Makoto Takimoto            NaN     1.48     50.0     25.0        1.1
Yoshiki Takahashi          NaN     0.00      0.0     66.0        2.3
Nobuhiko Takada            NaN     1.15     20.0      0.0        0.0
Mairbek Taisumov           NaN     1.34     63.0     88.0        0.0
Tatsuro Taira              NaN     2.35     47.0     62.0        2.1

                            DOB        win%
Name
Hunter Azure       Mar 02, 1992   81.818184
Bartosz Fabinski   Apr 26, 1986   75.000000
Wagnney Fabiano    Jul 14, 1975   80.000000
Brandon Davis      May 08, 1990   58.333332
Dave Galera        Jan 12, 1978   83.333336
...                         ...         ...
Makoto Takimoto    Dec 08, 1979   54.545456
Yoshiki Takahashi  Mar 13, 1969   50.000000
Nobuhiko Takada    Apr 12, 1962   20.000000
Mairbek Taisumov   Aug 08, 1988   81.818184
Tatsuro Taira      Jan 27, 2000  100.000000

[3473 rows x 22 columns]

In [15]:
fighters_clean.head()

,First,Last,Nickname,Ht,Wt,Reach,Stance,W,L,D,...,Str. Acc.,SApM,Str. Def,Unnamed: 15,TD Avg.,TD Acc.,TD Def.,Sub. Avg.,DOB,win%
Name,,,,,,,,,,,,,,,,,,,,,
Hunter Azure,Hunter,Azure,NaN,"5' 8""",145 lbs.,"69.0""",Orthodox,9,2,0,...,53.0,2.08,58.0,NaN,1.97,34.0,67.0,1.3,"Mar 02, 1992",81.818184
Bartosz Fabinski,Bartosz,Fabinski,The Butcher,"6' 0""",170 lbs.,"75.0""",Orthodox,15,5,0,...,68.0,1.46,51.0,NaN,7.10,70.0,80.0,0.0,"Apr 26, 1986",75.000000
Wagnney Fabiano,Wagnney,Fabiano,The Silencer,"5' 6""",145 lbs.,"69.0""",Southpaw,16,4,0,...,38.0,0.66,70.0,NaN,3.44,64.0,100.0,0.4,"Jul 14, 1975",80.000000
Brandon Davis,Brandon,Davis,Killer B,"5' 10""",135 lbs.,"72.0""",Orthodox,14,10,0,...,35.0,4.62,58.0,NaN,0.74,42.0,57.0,0.1,"May 08, 1990",58.333332
Dave Galera,Dave,Galera,Scarecrow,"5' 11""",135 lbs.,--,Orthodox,5,1,0,...,69.0,0.53,33.0,NaN,0.00,0.0,14.0,2.0,"Jan 12, 1978",83.333336

In [16]:
# use born year only
def get_year(dob):
    if pd.isna(dob):
        return "unk"
    return dob.split(", ")[-1]

fighters_clean["born_year"] = fighters_clean["DOB"].map(lambda dob: get_year(dob))

In [17]:
fighters_clean.head()

,First,Last,Nickname,Ht,Wt,Reach,Stance,W,L,D,...,SApM,Str. Def,Unnamed: 15,TD Avg.,TD Acc.,TD Def.,Sub. Avg.,DOB,win%,born_year
Name,,,,,,,,,,,,,,,,,,,,,
Hunter Azure,Hunter,Azure,NaN,"5' 8""",145 lbs.,"69.0""",Orthodox,9,2,0,...,2.08,58.0,NaN,1.97,34.0,67.0,1.3,"Mar 02, 1992",81.818184,1992
Bartosz Fabinski,Bartosz,Fabinski,The Butcher,"6' 0""",170 lbs.,"75.0""",Orthodox,15,5,0,...,1.46,51.0,NaN,7.10,70.0,80.0,0.0,"Apr 26, 1986",75.000000,1986
Wagnney Fabiano,Wagnney,Fabiano,The Silencer,"5' 6""",145 lbs.,"69.0""",Southpaw,16,4,0,...,0.66,70.0,NaN,3.44,64.0,100.0,0.4,"Jul 14, 1975",80.000000,1975
Brandon Davis,Brandon,Davis,Killer B,"5' 10""",135 lbs.,"72.0""",Orthodox,14,10,0,...,4.62,58.0,NaN,0.74,42.0,57.0,0.1,"May 08, 1990",58.333332,1990
Dave Galera,Dave,Galera,Scarecrow,"5' 11""",135 lbs.,--,Orthodox,5,1,0,...,0.53,33.0,NaN,0.00,0.0,14.0,2.0,"Jan 12, 1978",83.333336,1978

In [18]:
# remove unused columns
fighters_clean.drop(["DOB"], inplace=True, axis=1)
fighters_clean.drop(["Unnamed: 15", "First", "Last", "Nickname"], inplace=True, axis=1)
fighters_clean.drop(["Wt"], inplace=True, axis=1)
fighters_clean.drop(["Belt"], inplace=True, axis=1)

In [19]:
fighters_clean.head()

,Ht,Reach,Stance,W,L,D,SLpM,Str. Acc.,SApM,Str. Def,TD Avg.,TD Acc.,TD Def.,Sub. Avg.,win%,born_year
Name,,,,,,,,,,,,,,,,
Hunter Azure,"5' 8""","69.0""",Orthodox,9,2,0,3.92,53.0,2.08,58.0,1.97,34.0,67.0,1.3,81.818184,1992
Bartosz Fabinski,"6' 0""","75.0""",Orthodox,15,5,0,2.23,68.0,1.46,51.0,7.10,70.0,80.0,0.0,75.000000,1986
Wagnney Fabiano,"5' 6""","69.0""",Southpaw,16,4,0,1.19,38.0,0.66,70.0,3.44,64.0,100.0,0.4,80.000000,1975
Brandon Davis,"5' 10""","72.0""",Orthodox,14,10,0,4.68,35.0,4.62,58.0,0.74,42.0,57.0,0.1,58.333332,1990
Dave Galera,"5' 11""",--,Orthodox,5,1,0,1.67,69.0,0.53,33.0,0.00,0.0,14.0,2.0,83.333336,1978

In [20]:
bouts = pd.read_csv("bouts_721.csv")

Now, let's work on the fights dataset.

In [21]:
bouts.head()

,Event,Date,Location,W/L 1,W/L 2,Fighter 1,Fighter 2,Kd 1,Kd 2,Str 1,Str 2,Td 1,Td 2,Sub 1,Sub 2,Weight class,Method,Round,Time
0,UFC 304: Edwards vs. Muhammad 2,"July 27, 2024","Manchester, England, United Kingdom",NaN,NaN,Leon Edwards,Belal Muhammad,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Welterweight,NaN,NaN,NaN
1,UFC 304: Edwards vs. Muhammad 2,"July 27, 2024","Manchester, England, United Kingdom",NaN,NaN,Tom Aspinall,Curtis Blaydes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Heavyweight,NaN,NaN,NaN
2,UFC 304: Edwards vs. Muhammad 2,"July 27, 2024","Manchester, England, United Kingdom",NaN,NaN,King Green,Paddy Pimblett,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Lightweight,NaN,NaN,NaN
3,UFC 304: Edwards vs. Muhammad 2,"July 27, 2024","Manchester, England, United Kingdom",NaN,NaN,Muhammad Mokaev,Manel Kape,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Flyweight,NaN,NaN,NaN
4,UFC 304: Edwards vs. Muhammad 2,"July 27, 2024","Manchester, England, United Kingdom",NaN,NaN,Arnold Allen,Giga Chikadze,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Featherweight,NaN,NaN,NaN

In [22]:
# bouts = bouts[bouts['Event'] == 'UFC Fight Night: Lemos vs. Jandiroba']
bouts = bouts[bouts['Event'] != 'UFC 304: Edwards vs. Muhammad 2']

In [23]:
bouts["W/L 1"].value_counts()

W/L 1
win     7610
nc        86
draw      58
Name: count, dtype: int64

In [24]:
# use matches that have a winner, ignore nc, draws
bouts = bouts.loc[bouts["W/L 1"] == "win"].copy()

In [161]:
# bouts["Date"].map(lambda d: d[-4:])

In [162]:
bouts["fight_year"] = bouts["Date"].map(lambda d: d[-4:])
# bouts["Method"] = bouts["Method"].map(lambda m: m.split("-")[0])

In [25]:
# remove unused columns
bouts.drop(["W/L 1", "W/L 2"],
          axis=1, inplace=True)
# bouts.drop(["Date"],
#           axis=1, inplace=True)

# bouts.drop(["Kd 1", "Kd 2", "Str 1", "Str 2", "Td 1", "Td 2", "Sub 1", "Sub 2"],
#           axis=1, inplace=True)

In [26]:
bouts.head()

,Event,Date,Location,Fighter 1,Fighter 2,Kd 1,Kd 2,Str 1,Str 2,Td 1,Td 2,Sub 1,Sub 2,Weight class,Method,Round,Time
14,UFC Fight Night: Blanchfield vs. Fiorot,"March 30, 2024","Atlantic City, New Jersey, USA",Manon Fiorot,Erin Blanchfield,0,0,172,130,1,0,0,1,Women's Flyweight,U-DEC,5.0,5:00
15,UFC Fight Night: Blanchfield vs. Fiorot,"March 30, 2024","Atlantic City, New Jersey, USA",Joaquin Buckley,Vicente Luque,0,0,55,21,0,0,0,0,Welterweight,KO/TKO,2.0,3:17
16,UFC Fight Night: Blanchfield vs. Fiorot,"March 30, 2024","Atlantic City, New Jersey, USA",Chris Weidman,Bruno Silva,1,0,75,30,1,0,0,0,Middleweight,U-DEC,3.0,2:18
17,UFC Fight Night: Blanchfield vs. Fiorot,"March 30, 2024","Atlantic City, New Jersey, USA",Nursulton Ruziboev,Sedriques Dumas,1,0,12,1,0,0,0,0,Middleweight,KO/TKO,1.0,3:18
18,UFC Fight Night: Blanchfield vs. Fiorot,"March 30, 2024","Atlantic City, New Jersey, USA",Kyle Nelson,Bill Algeo,0,0,32,30,0,0,0,0,Featherweight,KO/TKO,1.0,4:00

In [27]:
# winner is always fighter 1
# bouts["Fighter1"].equals(bouts["winner"])
bouts["Winner"] = bouts["Fighter 1"]

In [28]:
bouts.head()

,Event,Date,Location,Fighter 1,Fighter 2,Kd 1,Kd 2,Str 1,Str 2,Td 1,Td 2,Sub 1,Sub 2,Weight class,Method,Round,Time,Winner
14,UFC Fight Night: Blanchfield vs. Fiorot,"March 30, 2024","Atlantic City, New Jersey, USA",Manon Fiorot,Erin Blanchfield,0,0,172,130,1,0,0,1,Women's Flyweight,U-DEC,5.0,5:00,Manon Fiorot
15,UFC Fight Night: Blanchfield vs. Fiorot,"March 30, 2024","Atlantic City, New Jersey, USA",Joaquin Buckley,Vicente Luque,0,0,55,21,0,0,0,0,Welterweight,KO/TKO,2.0,3:17,Joaquin Buckley
16,UFC Fight Night: Blanchfield vs. Fiorot,"March 30, 2024","Atlantic City, New Jersey, USA",Chris Weidman,Bruno Silva,1,0,75,30,1,0,0,0,Middleweight,U-DEC,3.0,2:18,Chris Weidman
17,UFC Fight Night: Blanchfield vs. Fiorot,"March 30, 2024","Atlantic City, New Jersey, USA",Nursulton Ruziboev,Sedriques Dumas,1,0,12,1,0,0,0,0,Middleweight,KO/TKO,1.0,3:18,Nursulton Ruziboev
18,UFC Fight Night: Blanchfield vs. Fiorot,"March 30, 2024","Atlantic City, New Jersey, USA",Kyle Nelson,Bill Algeo,0,0,32,30,0,0,0,0,Featherweight,KO/TKO,1.0,4:00,Kyle Nelson

In [31]:
# Reorder columns to make 'Name' the first column
# columns = [col for col in bouts.columns if col != 'Location' and col != 'Event'] + ['Event']+['Location']
# bouts = bouts[columns]
# columns = ['Winner'] + [col for col in bouts.columns if col != 'Winner']
# bouts = bouts[columns]
columns = [col for col in bouts.columns if col != 'Date'] + ['Date']
bouts = bouts[columns]
bouts.head()

,Winner,Fighter 1,Fighter 2,Kd 1,Kd 2,Str 1,Str 2,Td 1,Td 2,Sub 1,Sub 2,Weight class,Method,Round,Time,Event,Location,Date
14,Manon Fiorot,Manon Fiorot,Erin Blanchfield,0,0,172,130,1,0,0,1,Women's Flyweight,U-DEC,5.0,5:00,UFC Fight Night: Blanchfield vs. Fiorot,"Atlantic City, New Jersey, USA","March 30, 2024"
15,Joaquin Buckley,Joaquin Buckley,Vicente Luque,0,0,55,21,0,0,0,0,Welterweight,KO/TKO,2.0,3:17,UFC Fight Night: Blanchfield vs. Fiorot,"Atlantic City, New Jersey, USA","March 30, 2024"
16,Chris Weidman,Chris Weidman,Bruno Silva,1,0,75,30,1,0,0,0,Middleweight,U-DEC,3.0,2:18,UFC Fight Night: Blanchfield vs. Fiorot,"Atlantic City, New Jersey, USA","March 30, 2024"
17,Nursulton Ruziboev,Nursulton Ruziboev,Sedriques Dumas,1,0,12,1,0,0,0,0,Middleweight,KO/TKO,1.0,3:18,UFC Fight Night: Blanchfield vs. Fiorot,"Atlantic City, New Jersey, USA","March 30, 2024"
18,Kyle Nelson,Kyle Nelson,Bill Algeo,0,0,32,30,0,0,0,0,Featherweight,KO/TKO,1.0,4:00,UFC Fight Night: Blanchfield vs. Fiorot,"Atlantic City, New Jersey, USA","March 30, 2024"

In [168]:
# Reorder columns to make 'Name' the first column
columns = ['Winner'] + [col for col in bouts.columns if col != 'Winner']
bouts = bouts[columns]
bouts.head()

,Winner,Date,Fighter 1,Fighter 2,Kd 1,Kd 2,Str 1,Str 2,Td 1,Td 2,Sub 1,Sub 2,Weight class,Method,Round,Time,fight_year,Event,Location
14,Manon Fiorot,"March 30, 2024",Manon Fiorot,Erin Blanchfield,0,0,172,130,1,0,0,1,Women's Flyweight,U-DEC,5.0,5:00,2024,UFC Fight Night: Blanchfield vs. Fiorot,"Atlantic City, New Jersey, USA"
15,Joaquin Buckley,"March 30, 2024",Joaquin Buckley,Vicente Luque,0,0,55,21,0,0,0,0,Welterweight,KO/TKO,2.0,3:17,2024,UFC Fight Night: Blanchfield vs. Fiorot,"Atlantic City, New Jersey, USA"
16,Chris Weidman,"March 30, 2024",Chris Weidman,Bruno Silva,1,0,75,30,1,0,0,0,Middleweight,U-DEC,3.0,2:18,2024,UFC Fight Night: Blanchfield vs. Fiorot,"Atlantic City, New Jersey, USA"
17,Nursulton Ruziboev,"March 30, 2024",Nursulton Ruziboev,Sedriques Dumas,1,0,12,1,0,0,0,0,Middleweight,KO/TKO,1.0,3:18,2024,UFC Fight Night: Blanchfield vs. Fiorot,"Atlantic City, New Jersey, USA"
18,Kyle Nelson,"March 30, 2024",Kyle Nelson,Bill Algeo,0,0,32,30,0,0,0,0,Featherweight,KO/TKO,1.0,4:00,2024,UFC Fight Night: Blanchfield vs. Fiorot,"Atlantic City, New Jersey, USA"

In [169]:
for idx, col in enumerate(bouts.columns):
    print(f"Column '{col}' has index {idx}")

Column 'Winner' has index 0
Column 'Date' has index 1
Column 'Fighter 1' has index 2
Column 'Fighter 2' has index 3
Column 'Kd 1' has index 4
Column 'Kd 2' has index 5
Column 'Str 1' has index 6
Column 'Str 2' has index 7
Column 'Td 1' has index 8
Column 'Td 2' has index 9
Column 'Sub 1' has index 10
Column 'Sub 2' has index 11
Column 'Weight class' has index 12
Column 'Method' has index 13
Column 'Round' has index 14
Column 'Time' has index 15
Column 'fight_year' has index 16
Column 'Event' has index 17
Column 'Location' has index 18

In [75]:
# randomly swap fighter1 and fighter2 for half of the dataset to create "negative cases"
# swap_indices = np.random.choice(len(bouts), size = len(bouts) // 2, replace = False)
# bouts.iloc[swap_indices, [1, 2]] = bouts.iloc[swap_indices, [2, 1]].values
# bouts.iloc[swap_indices, [3, 4]] = bouts.iloc[swap_indices, [4, 3]].values
# bouts.iloc[swap_indices, [5, 6]] = bouts.iloc[swap_indices, [6, 5]].values
# bouts.iloc[swap_indices, [7, 8]] = bouts.iloc[swap_indices, [8, 7]].values
# bouts.iloc[swap_indices, [9, 10]] = bouts.iloc[swap_indices, [10, 9]].values
# bouts.head()

,Winner,Fighter 1,Fighter 2,Kd 1,Kd 2,Str 1,Str 2,Td 1,Td 2,Sub 1,Sub 2,Weight class,Method,Round,Time,fight_year,Event,Location
14,Manon Fiorot,Manon Fiorot,Erin Blanchfield,0,0,172,130,1,0,0,1,Women's Flyweight,U-DEC,5.0,5:00,2024,UFC Fight Night: Blanchfield vs. Fiorot,"Atlantic City, New Jersey, USA"
15,Joaquin Buckley,Joaquin Buckley,Vicente Luque,0,0,55,21,0,0,0,0,Welterweight,KO/TKO,2.0,3:17,2024,UFC Fight Night: Blanchfield vs. Fiorot,"Atlantic City, New Jersey, USA"
16,Chris Weidman,Chris Weidman,Bruno Silva,1,0,75,30,1,0,0,0,Middleweight,U-DEC,3.0,2:18,2024,UFC Fight Night: Blanchfield vs. Fiorot,"Atlantic City, New Jersey, USA"
17,Nursulton Ruziboev,Nursulton Ruziboev,Sedriques Dumas,1,0,12,1,0,0,0,0,Middleweight,KO/TKO,1.0,3:18,2024,UFC Fight Night: Blanchfield vs. Fiorot,"Atlantic City, New Jersey, USA"
18,Kyle Nelson,Bill Algeo,Kyle Nelson,0,0,30,32,0,0,0,0,Featherweight,KO/TKO,1.0,4:00,2024,UFC Fight Night: Blanchfield vs. Fiorot,"Atlantic City, New Jersey, USA"

In [32]:
bouts["Winner"] = bouts["Winner"] == bouts["Fighter 1"]
bouts["Winner"] = bouts["Winner"].astype(int)
bouts["Winner"].value_counts()

Winner
1    7610
Name: count, dtype: int64

In [171]:
bouts

,Winner,Date,Fighter 1,Fighter 2,Kd 1,Kd 2,Str 1,Str 2,Td 1,Td 2,Sub 1,Sub 2,Weight class,Method,Round,Time,fight_year,Event,Location
14,1,"March 30, 2024",Manon Fiorot,Erin Blanchfield,0,0,172,130,1,0,0,1,Women's Flyweight,U-DEC,5.0,5:00,2024,UFC Fight Night: Blanchfield vs. Fiorot,"Atlantic City, New Jersey, USA"
15,1,"March 30, 2024",Joaquin Buckley,Vicente Luque,0,0,55,21,0,0,0,0,Welterweight,KO/TKO,2.0,3:17,2024,UFC Fight Night: Blanchfield vs. Fiorot,"Atlantic City, New Jersey, USA"
16,1,"March 30, 2024",Chris Weidman,Bruno Silva,1,0,75,30,1,0,0,0,Middleweight,U-DEC,3.0,2:18,2024,UFC Fight Night: Blanchfield vs. Fiorot,"Atlantic City, New Jersey, USA"
17,1,"March 30, 2024",Nursulton Ruziboev,Sedriques Dumas,1,0,12,1,0,0,0,0,Middleweight,KO/TKO,1.0,3:18,2024,UFC Fight Night: Blanchfield vs. Fiorot,"Atlantic City, New Jersey, USA"
18,1,"March 30, 2024",Kyle Nelson,Bill Algeo,0,0,32,30,0,0,0,0,Featherweight,KO/TKO,1.0,4:00,2024,UFC Fight Night: Blanchfield vs. Fiorot,"Atlantic City, New Jersey, USA"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7763,1,"March 16, 2024",Jafel Filho,Ode Osbourne,0,0,21,0,1,0,2,0,Flyweight,SUB,1.0,4:27,2024,UFC Fight Night: Tuivasa vs. Tybura,"Las Vegas, Nevada, USA"
7764,1,"March 16, 2024",Danny Silva,Josh Culibao,0,0,45,87,4,0,1,0,Featherweight,S-DEC,3.0,5:00,2024,UFC Fight Night: Tuivasa vs. Tybura,"Las Vegas, Nevada, USA"
7765,1,"March 16, 2024",Jaqueline Amorim,Cory McKenna,0,0,3,4,0,1,4,0,Women's Strawweight,SUB,1.0,1:38,2024,UFC Fight Night: Tuivasa vs. Tybura,"Las Vegas, Nevada, USA"
7766,1,"March 16, 2024",Thiago Moises,Mitch Ramirez,1,0,25,16,2,0,1,0,Lightweight,KO/TKO,3.0,0:15,2024,UFC Fight Night: Tuivasa vs. Tybura,"Las Vegas, Nevada, USA"
7767,1,"March 16, 2024",Chad Anheliger,Charalampos Grigoriou,0,0,85,21,0,4,0,0,Bantamweight,U-DEC,3.0,5:00,2024,UFC Fight Night: Tuivasa vs. Tybura,"Las Vegas, Nevada, USA"

In [301]:
print(bouts[(bouts["Fighter 1"]=="Jean Silva") | (bouts["Fighter 2"]=="Jean Silva")])
print(bouts[(bouts["Fighter 1"]=="Bruno Silva") | (bouts["Fighter 2"]=="Bruno Silva")])
print(bouts[(bouts["Fighter 1"]=="Joey Gomez") | (bouts["Fighter 2"]=="Joey Gomez")])
print(bouts[(bouts["Fighter 1"]=="Tony Johnson") | (bouts["Fighter 2"]=="Tony Johnson")])
print(bouts[(bouts["Fighter 1"]=="Michael McDonald") | (bouts["Fighter 2"]=="Michael McDonald")])
# print(bouts[(bouts["Fighter 1"]=="Mike Davis") | (bouts["Fighter 2"]=="Mike Davis")])

      Winner         Fighter 1      Fighter 2 Kd 1 Kd 2 Str 1 Str 2 Td 1 Td 2  \
129        0        Drew Dober     Jean Silva    0    0    59    53    0    0
169        0  Charles Jourdain     Jean Silva    0    2    23    34    3    0
7639       1        Jean Silva  Westin Wilson    1    0    25    11    1    0

     Sub 1 Sub 2   Weight class  Method  Round  Time fight_year  \
129      0     0    Lightweight  KO/TKO    3.0  1:28       2024
169      0     0  Featherweight  KO/TKO    2.0  1:22       2024
7639     0     0  Featherweight  KO/TKO    1.0  4:12       2024

                    Location
129    Denver, Colorado, USA
169   Las Vegas, Nevada, USA
7639  Las Vegas, Nevada, USA
      Winner           Fighter 1          Fighter 2 Kd 1 Kd 2 Str 1 Str 2  \
14         0         Bruno Silva      Chris Weidman    0    1    30    75
5740       0         Bruno Silva       David Dvorak    0    0    45    67
5997       0         Bruno Silva    Tagir Ulanbekov    0    0    47    46
6231       0             JP Buys        Bruno Silva    0    3    17    37
6282       0    Victor Rodriguez        Bruno Silva    0    1     0     6
6364       1         Bruno Silva  Wellington Turman    0    0    19     1
6503       0      Andrew Sanchez        Bruno Silva    0    0    33    70
6585       0       Jordan Wright        Bruno Silva    0    1    20    19
6676       1        Alex Pereira        Bruno Silva    0    0   108    59
6945       1  Gerald Meerschaert        Bruno Silva    1    0    46    29
7209       0           Tyson Nam        Bruno Silva    0    1    12    23
7247       0        Brad Tavares        Bruno Silva    0    1    15    23
7362       1       Brendan Allen        Bruno Silva    1    0    30    20
7575       1     Shara Magomedov        Bruno Silva    0    0   113    65

     Td 1 Td 2 Sub 1 Sub 2  Weight class  Method  Round  Time fight_year  \
14      0    1     0     0  Middleweight       U    3.0  2:18       2024
5740    3    0     0     0     Flyweight       U    3.0  5:00       2020
5997    4    5     0     0     Flyweight       U    3.0  5:00       2020
6231    0    1     1     0     Flyweight  KO/TKO    2.0  2:56       2021
6282    0    0     0     0     Flyweight  KO/TKO    1.0  1:00       2021
6364    0    0     0     0  Middleweight  KO/TKO    1.0  4:45       2021
6503    7    0     0     0  Middleweight  KO/TKO    3.0  2:35       2021
6585    0    0     0     0  Middleweight  KO/TKO    1.0  1:28       2021
6676    0    2     0     0  Middleweight       U    3.0  5:00       2022
6945    1    0     1     0  Middleweight     SUB    3.0  1:39       2022
7209    0    0     0     1     Flyweight     SUB    2.0  1:23       2023
7247    0    0     0     0  Middleweight  KO/TKO    1.0  3:35       2023
7362    0    0     1     0  Middleweight     SUB    1.0  4:39       2023
7575    0    3     0     0  Middleweight       U    3.0  5:00       2023

                                        Location
14                Atlantic City, New Jersey, USA
5740          Brasilia, Distrito Federal, Brazil
5997  Abu Dhabi, Abu Dhabi, United Arab Emirates
6231                      Las Vegas, Nevada, USA
6282                      Las Vegas, Nevada, USA
6364                      Las Vegas, Nevada, USA
6503                      Las Vegas, Nevada, USA
6585                      Las Vegas, Nevada, USA
6676                      Las Vegas, Nevada, USA
6945                  San Diego, California, USA
7209                      Las Vegas, Nevada, USA
7247                      Las Vegas, Nevada, USA
7362                  Jacksonville, Florida, USA
7575  Abu Dhabi, Abu Dhabi, United Arab Emirates
      Winner      Fighter 1   Fighter 2 Kd 1 Kd 2 Str 1 Str 2 Td 1 Td 2 Sub 1  \
3749       0     Joey Gomez    Rob Font    0    1    15    52    1    1     0
4019       1  Jose Quinonez  Joey Gomez    2    1    56    44    5    0     0

     Sub 2  Weight class  Method  Round  Time fight_year  \
3749     0  Bantamweight  KO/TKO    2.0  4:13       2016
4019     0  Bantamweight       U    3.0  5:00       2016

                        Location
3749  Boston, Massachusetts, USA
4019         Hidalgo, Texas, USA
Empty DataFrame
Columns: [Winner, Fighter 1, Fighter 2, Kd 1, Kd 2, Str 1, Str 2, Td 1, Td 2, Sub 1, Sub 2, Weight class, Method, Round, Time, fight_year, Location]
Index: []
      Winner         Fighter 1          Fighter 2 Kd 1 Kd 2 Str 1 Str 2 Td 1  \
1776       0    Edwin Figueroa   Michael McDonald    0    0    45    51    0
1801       0     Chris Cariaso   Michael McDonald    0    0    44    32    1
1985       0         Alex Soto   Michael McDonald    0    2     6    12    0
2089       1  Michael McDonald      Miguel Torres    1    0    16     8    0
2379       1       Renan Barao   Michael McDonald    0    0    36    26    4
2539       0      Brad Pickett   Michael McDonald    0    2    17    51    1
2710       1      Urijah Faber   Michael McDonald    1    0    29     9    1
3737       1  Michael McDonald  Masanori Kanehara    0    0     5    15    0
3953       1      John Lineker   Michael McDonald    2    0    26    14    0

     Td 2 Sub 1 Sub 2  Weight class  Method  Round  Time fight_year  \
1776    5     0     3  Bantamweight       U    3.0  5:00       2011
1801    1     0     0  Bantamweight       S    3.0  5:00       2011
1985    0     0     0  Bantamweight  KO/TKO    1.0  0:56       2011
2089    0     0     0  Bantamweight  KO/TKO    1.0  3:18       2012
2379    0     1     0  Bantamweight     SUB    4.0  3:57       2013
2539    0     0     2  Bantamweight     SUB    2.0  3:43       2013
2710    0     1     0  Bantamweight     SUB    2.0  3:22       2013
3737    2     2     1  Bantamweight     SUB    2.0  2:09       2016
3953    0     0     0  Bantamweight  KO/TKO    1.0  2:43       2016

                             Location
1776         Seattle, Washington, USA
1801           Las Vegas, Nevada, USA
1985        San Jose, California, USA
2089            Atlanta, Georgia, USA
2379  London, England, United Kingdom
2539       Boston, Massachusetts, USA
2710      Sacramento, California, USA
3737           Las Vegas, Nevada, USA
3953   Sioux Falls, South Dakota, USA

In [33]:
# again, handel duplicate names
bouts_clean = bouts.copy()
for col in ["Fighter 1", "Fighter 2"]:
    bouts_clean.loc[(bouts_clean[col] == "Michael McDonald") &
                    (bouts_clean["Weight class"] == "Light Heavyweight"), col] = "Michael McDonald 205"
    bouts_clean.loc[(bouts_clean[col] == "Tony Johnson") &
                    (bouts_clean["Weight class"] == "Heavyweight"), col] = "Tony Johnson 265"
    bouts_clean.loc[(bouts_clean[col] == "Bruno Silva") &
                    (bouts_clean["Weight class"] == "Middleweight"), col] = "Bruno Silva 185"
    # bouts_clean.loc[(bouts_clean[col] == "Mike Davis") &
    #                 (bouts_clean["Weight class"] == "Lightweight"), col] = "Mike Davis 155"

In [125]:
# bouts_clean = bouts.copy()
# for col in ["Fighter 1", "Fighter 2"]:
#     bouts_clean.loc[(bouts_clean[col] == "Mike Davis") &
#                     (bouts_clean["Weight class"] == "Lightweight"), col] = "Mike Davis 155"

In [126]:
# bouts_clean[bouts_clean["fighter1"] == "Dong Hyun Kim 155"]
# fighters_clean.drop('Jean Silva 160', inplace=True)
# df = df[df['Name'] != 'Jean Silva 160']
# fighters_clean = fighters_clean[fighters_clean.index != 'Jean Silva 160']
print(fighters_clean[fighters_clean.index == 'Mike Davis'])

               Ht  Reach    Stance   W  L  D  SLpM  Str. Acc.  SApM  Str. Def  \
Name
Mike Davis  6' 0"  72.0"  Orthodox  11  2  0  5.35       52.0  5.76      55.0

            TD Avg.  TD Acc.  TD Def.  Sub. Avg.       win% born_year
Name
Mike Davis     2.77     53.0     64.0        0.4  84.615387      1992

Next, we need to fuse these two datasets together.

In [173]:
# make sure all fighters are in the figher database
# otherwise remove the corresponding bout
all_fighter_names = fighters_clean.index.values.tolist()

bouts_clean = bouts_clean.loc[(bouts_clean["Fighter 1"].isin(all_fighter_names)) &
                              (bouts_clean["Fighter 2"].isin(all_fighter_names))]

In [174]:
bouts_clean.reset_index(inplace=True, drop=True)

In [34]:
bouts_clean.head()

,Winner,Fighter 1,Fighter 2,Kd 1,Kd 2,Str 1,Str 2,Td 1,Td 2,Sub 1,Sub 2,Weight class,Method,Round,Time,Event,Location,Date
14,1,Manon Fiorot,Erin Blanchfield,0,0,172,130,1,0,0,1,Women's Flyweight,U-DEC,5.0,5:00,UFC Fight Night: Blanchfield vs. Fiorot,"Atlantic City, New Jersey, USA","March 30, 2024"
15,1,Joaquin Buckley,Vicente Luque,0,0,55,21,0,0,0,0,Welterweight,KO/TKO,2.0,3:17,UFC Fight Night: Blanchfield vs. Fiorot,"Atlantic City, New Jersey, USA","March 30, 2024"
16,1,Chris Weidman,Bruno Silva 185,1,0,75,30,1,0,0,0,Middleweight,U-DEC,3.0,2:18,UFC Fight Night: Blanchfield vs. Fiorot,"Atlantic City, New Jersey, USA","March 30, 2024"
17,1,Nursulton Ruziboev,Sedriques Dumas,1,0,12,1,0,0,0,0,Middleweight,KO/TKO,1.0,3:18,UFC Fight Night: Blanchfield vs. Fiorot,"Atlantic City, New Jersey, USA","March 30, 2024"
18,1,Kyle Nelson,Bill Algeo,0,0,32,30,0,0,0,0,Featherweight,KO/TKO,1.0,4:00,UFC Fight Night: Blanchfield vs. Fiorot,"Atlantic City, New Jersey, USA","March 30, 2024"

In [35]:
bouts_clean.to_csv("ufc_bouts_clean.csv")

In [176]:
print("{0} bouts in total, after clean up: {1} bouts".format(len(bouts), len(bouts_clean)))

7610 bouts in total, after clean up: 7412 bouts

In [177]:
fighter1_data = fighters_clean.loc[bouts_clean["Fighter 1"]]
fighter1_data = fighter1_data.add_suffix(' 1')
fighter2_data = fighters_clean.loc[bouts_clean["Fighter 2"]]
fighter2_data = fighter2_data.add_suffix(' 2')

In [178]:
fighter1_data.head()

,Ht 1,Reach 1,Stance 1,W 1,L 1,D 1,SLpM 1,Str. Acc. 1,SApM 1,Str. Def 1,TD Avg. 1,TD Acc. 1,TD Def. 1,Sub. Avg. 1,win% 1,born_year 1
Name,,,,,,,,,,,,,,,,
Manon Fiorot,"5' 7""","65.0""",Orthodox,12,1,0,6.26,41.0,3.77,68.0,1.17,42.0,93.0,0.0,92.307693,1990
Joaquin Buckley,"5' 10""","76.0""",Southpaw,19,6,0,4.25,36.0,3.12,58.0,1.69,44.0,69.0,0.0,76.000000,1994
Chris Weidman,"6' 2""","78.0""",Orthodox,16,7,0,3.18,45.0,3.22,51.0,3.44,42.0,65.0,0.8,69.565216,1984
Nursulton Ruziboev,"6' 5""","76.0""",Orthodox,34,9,2,2.50,43.0,4.60,49.0,0.77,100.0,0.0,0.0,75.555557,1993
Kyle Nelson,"5' 11""","71.0""",Switch,16,5,1,3.65,45.0,4.69,52.0,1.10,20.0,73.0,0.6,72.727272,1991

In [179]:
fighter2_data.head()

,Ht 2,Reach 2,Stance 2,W 2,L 2,D 2,SLpM 2,Str. Acc. 2,SApM 2,Str. Def 2,TD Avg. 2,TD Acc. 2,TD Def. 2,Sub. Avg. 2,win% 2,born_year 2
Name,,,,,,,,,,,,,,,,
Erin Blanchfield,"5' 4""","66.0""",Orthodox,12,2,0,5.47,45.0,4.34,58.0,2.05,33.0,81.0,1.0,85.714287,1999
Vicente Luque,"5' 11""","75.0""",Orthodox,22,10,1,5.07,52.0,5.21,52.0,1.00,53.0,62.0,0.6,66.666664,1991
Bruno Silva 185,"6' 0""","74.0""",Orthodox,23,11,0,4.12,49.0,5.45,41.0,0.93,27.0,73.0,0.0,67.647057,1989
Sedriques Dumas,"6' 2""","79.0""",Orthodox,9,2,0,1.76,45.0,2.14,57.0,0.71,50.0,40.0,0.4,81.818184,1995
Bill Algeo,"6' 0""","73.0""",Switch,18,8,0,6.16,52.0,4.52,47.0,0.86,46.0,56.0,0.1,69.230766,1989

In [180]:
len(fighter1_data), len(fighter2_data)

(7412, 7412)

In [181]:
# now join the two datasets together
fighter1_data.reset_index(inplace=True, drop=True)
fighter2_data.reset_index(inplace=True, drop=True)
combined = pd.concat([bouts_clean, fighter1_data, fighter2_data], axis=1, sort=False)

In [182]:
combined.head()

,Winner,Date,Fighter 1,Fighter 2,Kd 1,Kd 2,Str 1,Str 2,Td 1,Td 2,...,SLpM 2,Str. Acc. 2,SApM 2,Str. Def 2,TD Avg. 2,TD Acc. 2,TD Def. 2,Sub. Avg. 2,win% 2,born_year 2
0,1,"March 30, 2024",Manon Fiorot,Erin Blanchfield,0,0,172,130,1,0,...,5.47,45.0,4.34,58.0,2.05,33.0,81.0,1.0,85.714287,1999
1,1,"March 30, 2024",Joaquin Buckley,Vicente Luque,0,0,55,21,0,0,...,5.07,52.0,5.21,52.0,1.00,53.0,62.0,0.6,66.666664,1991
2,1,"March 30, 2024",Chris Weidman,Bruno Silva 185,1,0,75,30,1,0,...,4.12,49.0,5.45,41.0,0.93,27.0,73.0,0.0,67.647057,1989
3,1,"March 30, 2024",Nursulton Ruziboev,Sedriques Dumas,1,0,12,1,0,0,...,1.76,45.0,2.14,57.0,0.71,50.0,40.0,0.4,81.818184,1995
4,1,"March 30, 2024",Kyle Nelson,Bill Algeo,0,0,32,30,0,0,...,6.16,52.0,4.52,47.0,0.86,46.0,56.0,0.1,69.230766,1989

In [183]:
len(combined)

7412

In [184]:
combined.to_csv("ufc_combined_726.csv")